/**
 * Framework Plugin Interface
 *
 * All plugins must implement this interface.
 * This contract defines what the framework expects from every plugin.
 */

import type { Bundle } from "../bundles/types.js";
import type { LLMClient } from "../llm/llm-config";

/**
 * Plugin specification defines how to generate a report
 */
export interface PluginSpec {
  /** Specification ID */
  id: string;

  /** Plugin ID */
  pluginId: string;

  /** Template to use */
  template: string;

  /** Data source path */
  dataSource: string;

  /** Output format */
  outputFormat: "html" | "markdown" | "pdf";

  /** Additional options */
  options?: Record<string, any>;
}

/**
 * Report generated by a plugin
 */
export interface PluginReport {
  /** Report ID */
  id: string;

  /** Report title */
  title: string;

  /** Report content (Markdown) */
  content: string;

  /** Metadata */
  metadata?: {
    totalTokens?: number;
    [key: string]: any;
  };
}

export interface FrameworkPlugin {
  /**
   * Unique identifier for this plugin
   * Examples: "patent", "pubmed", "staffing", "disease", "financial"
   */
  readonly id: string;

  /**
   * Semantic version of the plugin
   */
  readonly version: string;

  /**
   * Human-readable description of what this plugin does
   */
  readonly description: string;

  /**
   * Initialize the plugin with framework configuration
   *
   * @param config - Framework configuration (optional)
   */
  initialize?(config?: any): Promise<void>;

  /**
   * Generate a report using the plugin
   *
   * @param spec - Plugin specification
   * @param bundle - Input data bundle
   * @param llmClient - LLM client to use for generating text
   * @returns Generated report
   */
  generate(
    spec: PluginSpec,
    bundle: Bundle<any>,
    llmClient: LLMClient
  ): Promise<PluginReport>;

  /**
   * Ingest data from a file and return a standardized Bundle
   *
   * @param filePath - Path to the input file
   * @returns Promise<Bundle> - Standardized data container
   */
  ingestFromFile(filePath: string): Promise<Bundle<any>>;

  /**
   * Return all available specifications for this plugin
   *
   * @returns Record<string, string> - Map of specificationId -> YAML content
   */
  getSpecifications(): Record<string, string>;

  /**
   * Return the path to the directory containing prompt files
   *
   * @returns string - Absolute path to prompts directory
   */
  getPromptsDir(): string;

  /**
   * Return the path to the directory containing template files
   *
   * @returns string - Absolute path to templates directory
   */
  getTemplatesDir(): string;
}

/**
 * Plugin Metadata (for discovery and listing)
 */
export interface PluginMetadata {
  id: string;
  version: string;
  description: string;
  author?: string;
  specifications: string[]; // Available specification IDs
}
